-- 2022.01.25

-- 기본 테이블 생성 쿼리 

CREATE TABLE TB_DWG_COLLECT_MATINFO_PROJECT
(
ID INT IDENTITY(1,1) NOT NULL,
CD_PROJ NVARCHAR(20) NULL,
NM_PROJ NVARCHAR(255) NULL,
NM_SHEET NVARCHAR(255) NULL,
TYP_SHEET NVARCHAR(50) NULL,
ID_CREATE NVARCHAR(20) NULL,
DT_CREATE datetime NULL
PRIMARY KEY(ID)
)



CREATE TABLE TB_DWG_COLLECT_ROOM_MATINFO_PROJECT_ROW
(
ID INT IDENTITY(1,1) NOT NULL,
ID_PROJ INT NOT NULL,
NUM_ROW INT NULL,
JSON_ROW NVARCHAR(MAX) NULL,
ID_CREATE NVARCHAR(20) NULL,
DT_CREATE datetime NULL
PRIMARY KEY(ID),
FOREIGN KEY(ID_PROJ) REFERENCES TB_DWG_COLLECT_ROOM_MATINFO_PROJECT(ID)
)